POST http://localhost:3000/register/
Content-Type: application/json 

{
  "username": "chirayu123456",
  "password": "richard",
  "name": "chirayu humar",
  "gender": "male"
}

###api2
POST http://localhost:3000/login/
Content-Type: application/json 

{
  "username":"chirayu123456",
  "password":"richard"
}

###api3
GET http://localhost:3000/user/tweets/feed/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg1MDgwMTA0fQ.TyZI-Eq7x4CL9r0u55LnC600DArDD8Q0NRlx1htAdHg

###api4 
GET http://localhost:3000/user/following/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg1MDgwMTA0fQ.TyZI-Eq7x4CL9r0u55LnC600DArDD8Q0NRlx1htAdHg 

###api5 
GET http://localhost:3000/user/followers/ 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg1MDgwMTA0fQ.TyZI-Eq7x4CL9r0u55LnC600DArDD8Q0NRlx1htAdHg 

###api6 
GET http://localhost:3000/tweets/1/ 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg1MDgwMTA0fQ.TyZI-Eq7x4CL9r0u55LnC600DArDD8Q0NRlx1htAdHg 

###api7
GET http://localhost:3000/tweets/1/likes/ 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg1MDgwMTA0fQ.TyZI-Eq7x4CL9r0u55LnC600DArDD8Q0NRlx1htAdHg

###api8 
GET http://localhost:3000/tweets/1/replies/ 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg1MDgwMTA0fQ.TyZI-Eq7x4CL9r0u55LnC600DArDD8Q0NRlx1htAdHg

###api9
GET http://localhost:3000/user/tweets/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg1MDgwMTA0fQ.TyZI-Eq7x4CL9r0u55LnC600DArDD8Q0NRlx1htAdHg 

###api10
POST http://localhost:3000/user/tweets/ 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg1MDgwMTA0fQ.TyZI-Eq7x4CL9r0u55LnC600DArDD8Q0NRlx1htAdHg 

{
   "tweet": "The Mornings..."
}

###api11 
DELETE http://localhost:3000/tweets/5/
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg1MDgwMTA0fQ.TyZI-Eq7x4CL9r0u55LnC600DArDD8Q0NRlx1htAdHg 

###